### ISSUE TITLE
It is possible to accidentally collapse step rows that follow a failed step

### ISSUE THREAD

**Issue by AngryPidgeon** [leinonen/cucumber-html-report#10] opened 2016-04-26 21:07 UTC
To reproduce this, open a failed step to show the error.  Then click on the newly-visible error row with the message.  This will hide the following step.  See attached screens.  Should be an ez fix.

![screen shot 2016-04-26 at 2 05 29 pm](https://cloud.githubusercontent.com/assets/16108887/14834209/1598786a-0bb8-11e6-82a2-ec8790c26061.png)

--

![screen shot 2016-04-26 at 2 05 33 pm](https://cloud.githubusercontent.com/assets/16108887/14834213/1ae67952-0bb8-11e6-956f-94d658edd5b0.png)

--

![screen shot 2016-04-26 at 2 05 37 pm](https://cloud.githubusercontent.com/assets/16108887/14834218/207055c8-0bb8-11e6-8461-48d8ee15641d.png)

**Comment by AngryPidgeon** [comment] 2016-04-26 21:08
^ In the screenshots above notice that I managed to collapse the step on Line 10 by clicking the big red error stack trace part of the table.  This should be fixable in the JS part of the template with an if-statement.

**Comment by floverdevel** [comment] 2016-05-12 02:40
easy-fix should be to do not add the "failed" css class to the newly-visible table-row.
i should have add "failure-detail" class instead so it could have a different color and style than "failed".

**Comment by floverdevel** [comment] 2016-05-12 02:45
the bug is caused by this commit :
https://github.com/leinonen/cucumber-html-report/commit/42c561ba3f51d0c7d20608ccbd6cf2857b79c50c

easy fix is to revert this commit

**Comment by AngryPidgeon** [comment] 2016-05-12 17:36
I think this has been patched since I opened it.

**Comment by leinonen** [comment] 2016-05-19 18:44
Closing it :)

**Closed by leinonen** 2016-05-19 18:44 UTC
